//LocalHost

### getAll

GET http://localhost:8080/contacts/

### getById

GET http://localhost:8080/contacts/65a9e4729b3c624ca2c691ec

### insertOne

POST http://localhost:8080/contacts/insertOne HTTP/1.1
Content-Type: application/json

{
  "firstName": "TestName",
  "lastName": "testing",
  "email": "brian@gmail.com",
  "favoriteColor": "blue",
  "birthday": "June 22"
}

###  updateOne

PUT http://localhost:8080/contacts/id-to-modify/65ae83b04b0bc18462f028d6 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Star"
}

### deleteOne

DELETE http://localhost:8080/contacts/delete/65ae83b04b0bc18462f028d6





// Web Request

### getAll

GET https://contacts-qk5v.onrender.com/contacts

### getById

GET https://contacts-qk5v.onrender.com/contacts/65a9e4729b3c624ca2c691ec

### insertOne

POST https://contacts-qk5v.onrender.com/contacts/insertOne HTTP/1.1
Content-Type: application/json

{
  "firstName": "Web",
  "lastName": "Name",
  "email": "brian@gmail.com",
  "favoriteColor": "blue",
  "birthday": "June 1"
}

### updateOne

PUT https://contacts-qk5v.onrender.com/contacts/id-to-modify/65ae83b04b0bc18462f028d6 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Brenda"
}

### delete

DELETE https://contacts-qk5v.onrender.com/contacts/delete/65ae83b04b0bc18462f028d6